export const ROUTES = {
  HOME: "/",
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    VERIFY_OTP: "/verify-otp",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  CONTEST: {
    CONTEST: "/contest",
    MY_CONTEST: "/my-contest",
    CONTEST_DETAILS: "/contest/details",
    CONTEST_WINNERS: "/contest/winners",
  },
  EXAM: {
    INSTRUCTION: "/exam/instruction",
    QUESTION: "/exam/question",
    RESULT: "/exam/result",
    MISTAKE_MAP_REPORT: "/exam/mistake-map-report/:id",
    SOLUTION: "/exam/solution/:id",
    COUNT_DOWN: "/exam/count-down"
  },
  KYC: {
    KYC: "/kyc",
    KYC_REGISTER: "/kyc/register",
    KYC_VERIFICATION: "/kyc/verification",
  },
  RECHARGE: { RECHARGE: "/recharge" },
  MY_INFO: { MY_INFO: "/my-info" },
  GET_SCHOLARSHIP: { GET_SCHOLARSHIP: "/get-scholarship" },
  HISTORY: { HISTORY: "/history" },
  HOW_IT_WORK: { HOW_IT_WORK: "/how-it-work" },
  ABOUT_US: { ABOUT_US: "/about-us" },
  ILLEGALITY: { ILLEGALITY: "/illegality" },
  PRIVACY_POLICY: { PRIVACY_POLICY: "/privacy-policy" },
  TERMS_CONDITIONS: { TERMS_CONDITIONS: "/terms-conditions" },
  REFERRAL: { REFERRAL: "/referral" },
  FULL_FEST_REPORT: { FULL_FEST_REPORT: "/full-fest-report" },
  CLASSES: { CLASSES: "/classes" },
  COURSE: {
    COURSE: "/course",
    DETAILS: "/course/details/:id",
  },
  WORKSHOP: { WORKSHOP: "/workshop", DETAILS: "/workshop/details/:id" },
  YOUTUBE_VALUES: { YOUTUBE_VALUES: "/youtube-values" },
  SOCIAL_MEDIA_ENGAGE: { SOCIAL_MEDIA_ENGAGE: "/social-media-engage" },
  CONTACT: { CONTACT: "/contact" },
} as const;
